from typing import Optional, Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from operator import add
from app.domain.data_models import (
    PRMetadata, PRFile,
    QualityReview, SecurityReview, PerformanceReview
)


def keep_last(existing, new):
    """
    Reducer function designed to retain the most recent state mutation.
    This is essential for resolving conflicts during parallel node executions by prioritizing the latest written data.
    """
    return new if new is not None else existing


class GraphState(TypedDict):
    # ── Immutable Context ────────────────────────────
    # Parameters defining the scope of the operation. These fields remain static after initialization.
    pr_number: int
    repo_full_name: str

    # ── Repository Artifacts ─────────────────────────
    # Data fetched directly from the upstream version control system.
    pr_metadata: Optional[PRMetadata]
    pr_files: Optional[list[PRFile]]
    pr_diff_text: Optional[str]

    # ── Analysis Payloads ────────────────────────────
    # Domain-specific review artifacts generated by individual processing agents.
    # We employ `Annotated` coupled with our reducer `keep_last` to ensure thread-safe state convergence.
    quality_review: Annotated[Optional[QualityReview], keep_last]
    security_review: Annotated[Optional[SecurityReview], keep_last]
    performance_review: Annotated[Optional[PerformanceReview], keep_last]

    # ── Synthesized Output ───────────────────────────
    final_comment: Optional[str]

    # ── Execution Metadata ───────────────────────────
    error: Optional[str]
    messages: Annotated[list, add_messages]